Blacklist tenacity 8.2.0
It breaks type-checking: https://github.com/jd/tenacity/issues/389

```
swh/storage/cassandra/cql.py:301: error: Argument 1 has incompatible type "Callable[[CqlRunner, Any, Optional[Sequence[Any]]], Any]"; expected <nothing>
swh/storage/cassandra/cql.py:309: error: Argument 1 has incompatible type "Callable[[CqlRunner, Any, Sequence[Tuple[Any, ...]]], Iterable[Dict[str, Any]]]"; expected <nothing>
swh/storage/cassandra/cql.py:321: error: <nothing> not callable
swh/storage/cassandra/cql.py:327: error: <nothing> not callable
swh/storage/cassandra/cql.py:338: error: <nothing> not callable
[...]
swh/storage/cassandra/cql.py:1482: error: <nothing> not callable
swh/storage/proxies/retry.py:70: error: Need type annotation for "swh_retry"
swh/storage/tests/test_cassandra_migration.py:77: error: <nothing> not callable
swh/storage/tests/test_cassandra_migration.py:96: error: <nothing> not callable
swh/storage/tests/test_cassandra_migration.py:209: error: <nothing> not callable
swh/storage/tests/test_cassandra_migration.py:229: error: <nothing> not callable
Found 65 errors in 3 files (checked 91 source files)
```