Make test_content_add_race fail for the right reason.
Since 209de5dbaa127dacd114fbbd084f22632982eb77, it was failing because of:
TypeError("content_add() got an unexpected keyword argument 'db'")