pytest_plugin: Fix cassandra startup on debian 13
Debian 13 bumped OpenJDK to 21 which prevents cassandra to start as the following
exception is raised at startup:

java.lang.UnsupportedOperationException: The Security Manager is deprecated and
will be removed in a future release

Add -Djava.security.manager=allow to JVM options to workaround the issue and allow
to execute the cassandra tests.